config/routes.rb
Rails.application.routes.draw do
  devise_for :admins, controllers: {
    sessions: 'admins/sessions',
    passwords: 'admins/sessions',
    registrations: 'admins/registrations',
  }
  # devise customersと被らないよう指定

  namespace :admin do
    root 'homes#top'
    resources :genres, only: [:index, :create, :edit, :update, :destroy]
    resources :customers, only: [:index, :show, :edit, :update]
      resources :movies, only: [:index, :new, :create, :show, :edit, :update] do
      resources :movie_comments, only: [:show, :update, :index, :edit, :destroy, :create]
      resource :favorites, only: [:create, :destroy]
    end
  end

  devise_for :customers, controllers: {
    sessions: 'customers/sessions',
    passwords: 'customers/sessions',
    registrations: 'customers/registrations',
  }
  get 'search/search'


  scope module: :public do
   root 'homes#top'
   get 'homes/about' => 'homes#about'
     resources :movies, only: [:new, :create, :index, :show, :create, :update] do
     resources :movie_comments, only: [:index, :show, :destroy, :create]
     resource :favorites, only: [:create, :destroy]
   end
   resources :customers, only: [:show, :edit, :update] do
   resource :relationships, only: [:create, :destroy]
   get 'mypage' => 'customers#mypage', as: 'mypage'
   get 'followings' => 'relationships#followings', as: 'followings'
   get 'followers' => 'relationships#followers', as: 'followers'
  member do
    patch 'withdrawal'
    get 'unsubscribe'
   end
  end
 end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/admin/movies_controller.rb
class Admin::MoviesController < ApplicationController
  before_action :authenticate_admin!

  def index
    @movies = Movie.all
    @q = Movie.ransack(params[:q])
     # params[:q] = ユーザーが記入したキーワード
    @movies = @q.result(distinct: true)
     # distinct = 重複レコードを一つにまとめる
     # rusult = レコードリレーションを返す
  end

  def new
    @movie = Movie.new
  end

  def create
    @movie = Movie.new(movie_params)
    @movie.save!
    redirect_to movies_path
  end

  def show
    @movie_comments = MovieComment.all
    @movie = Movie.find(params[:id])
    @movie_comment = MovieComment.new
    @customer = Customer.find_by(id: params[:id])
    # find_by = 指定したレコードを一つ探す
  end

  def edit
    @movie = Movie.find(params[:id])
  end

  def update
     @movie = Movie.find(params[:id])
    if @movie.update(movie_params)
     redirect_to movies_path
    else
     render "edit"
    end
  end

  private

  def movie_params
    params.require(:movie).permit(:customer_id, :genre_id, :image, :title, :director, :actor, :explain, :cast, :actres, :quote, :point)
  end
end

app/helpers/admin/movies_helper.rb
module Admin::MoviesHelper
end

app/views/admin/movies/edit.html.erb
<div class="container">
  <div class="row">
   <div class="col-md-8 mx-auto">
     <div class="my-3 ">作品編集</div>
<%= form_with model: @movie, url: {controller: 'admin/movies', action: 'update' }, local:true do |f| %>

<table class="table table-borderless bl-3">
<tr>
<th class="text-right"><%= f.label :"ジャンル" %></th>
<th><%= f.collection_select :genre_id, Genre.all, :id, :name, include_blank:"  --選択してください--  " %></th>
<!-- ジャンル入力項目を反映 -->
</tr>

<tr>
<th class="text-right"><%= f.label :"作品名" %></th>
<th><%= f.text_field :title, autofocus: true, autocomplete: "title", placeholder:"作品名", size: 31 %></th>
</tr>

<tr>
<th class="text-right"><%= f.label :image, "作品画像" %></th>
<th><%= f.attachment_field :image %></th>
</tr>



<tr>
<th class="text-right"><%= f.label :"監督名" %></th>
<th><%= f.text_field :director, autofocus: true, autocomplete: "director", placeholder:"監督名", size: 31 %></th>
</tr>


<tr>
<th class="text-right"><%= f.label :"主演" %></th>
<th><%= f.text_field :actor, autofocus: true, autocomplete: "actor", placeholder:"主演", size: 31 %></th>
</tr>


<tr>
<th class="text-right"><%= f.label :"女優" %></th>
<th><%= f.text_field :actres, autofocus: true, autocomplete: "actres", placeholder:"女優", size: 31 %></th>
</tr>


<tr>
<th class="text-right"><%= f.label :"キャスト" %></th>
<th><%= f.text_field :cast, autofocus: true, autocomplete: "cast", placeholder:"キャスト", size: 31 %></th>
</tr>


<tr>
<th class="text-right"><%= f.label :"引用元" %></th>
<th><%= f.text_field :quote, autofocus: true, autocomplete: "引用元", placeholder:"引用元", size: 31 %></th>
</tr>

<tr>
<th class="text-right"><%= f.label :"豆知識" %></th>
<th><%= f.text_area :point, autofocus: true, autocomplete: "豆知識", placeholder:"豆知識", size: 31 %></th>
</tr>

<tr>
<th class="text-right"><%= f.label :"あらすじ" %></th>
<th><%= f.text_area :explain, autofocus: true, autocomplete: "explain", placeholder:"あらすじ", size: 31 %></th>
</tr>


<tr>
  <th></th>
<th><%= f.submit "変更を保存", class: "btn btn-success" %></th>
</tr>

</table>
<% end %>

 </div>
  </div>
</div>

app/views/admin/movies/index.html.erb
<div class="row">
<% @movies.each do |movie| %>
<div class="col-md-2">
<div class="card">
	  <%= link_to attachment_image_tag(movie, :image, format: 'jpeg', size: "213x263", fallback: "no_image.jpg"), movie_movie_comments_path(movie) %>
<div class="card-body text-center">
<h6 class="card-title">
  <strong><%= movie.title %></strong>
  </h6>

<p class="card-text">
<%= link_to movie_movie_comments_path(movie), class: "button card-footer-item" do %>
 <i class="fas fa-eye"></i>
<% end %>
<%= link_to edit_admin_movie_path(movie), class: "button card-footer-item" do %>
<i class="fas fa-edit"></i>
<% end %>
</p>

</div>

</div>
</div>
<% end %>

app/views/admin/movies/new.html.erb
<div class="container">
  <div class="row">
   <div class="col-md-8 mx-auto">
     <div class="my-3 ">作品登録</div>
<%= form_with model: @movie, url: {controller: 'admin/movies', action: 'create' }, local:true do |f| %>



<table class="table table-borderless bl-3">
<tr>
<th class="text-right"><%= f.label :"ジャンル" %></th>
<th><%= f.collection_select :genre_id, Genre.all, :id, :name, include_blank:"  --選択してください--  " %></th>
<!-- ジャンル入力項目を反映 -->
</tr>

<tr>
<th class="text-right"><%= f.label :"作品名" %></th>
<th><%= f.text_field :title, autofocus: true, autocomplete: "title", placeholder:"作品名", size: 31 %></th>
</tr>

<tr>
<th class="text-right"><%= f.label :image, "作品画像" %></th>
<th><%= f.attachment_field :image %></th>
</tr>



<tr>
<th class="text-right"><%= f.label :"監督名" %></th>
<th><%= f.text_field :director, autofocus: true, autocomplete: "director", placeholder:"監督名", size: 31 %></th>
</tr>


<tr>
<th class="text-right"><%= f.label :"主演" %></th>
<th><%= f.text_field :actor, autofocus: true, autocomplete: "actor", placeholder:"主演", size: 31 %></th>
</tr>


<tr>
<th class="text-right"><%= f.label :"女優" %></th>
<th><%= f.text_field :actres, autofocus: true, autocomplete: "actres", placeholder:"女優", size: 31 %></th>
</tr>


<tr>
<th class="text-right"><%= f.label :"キャスト" %></th>
<th><%= f.text_field :cast, autofocus: true, autocomplete: "cast", placeholder:"キャスト", size: 31 %></th>
</tr>


<tr>
<th class="text-right"><%= f.label :"引用元" %></th>
<th><%= f.text_field :quote, autofocus: true, autocomplete: "引用元", placeholder:"引用元", size: 31 %></th>
</tr>

<tr>
<th class="text-right"><%= f.label :"豆知識" %></th>
<th><%= f.text_area :point, autofocus: true, autocomplete: "豆知識", placeholder:"豆知識", size: 31 %></th>
</tr>


<tr>
<th class="text-right"><%= f.label :"あらすじ" %></th>
<th><%= f.text_area :explain, autofocus: true, autocomplete: "explain", placeholder:"あらすじ", size: 31 %></th>
</tr>


<tr>
  <th></th>
<th><%= f.submit "新規登録", class: "btn btn-success" %></th>
</tr>

</table>
<% end %>

 </div>
  </div>
</div>

app/views/admin/movies/show.html.erb
<h2>作品詳細</h2>

<h4>ジャンル</h4>
<%= @movie.genre.name %>

<h4>作品名</h4>
<%= @movie.title %>

<h4>作品画像</h4>
<%= attachment_image_tag(@movie, :image, size: "150×200", fallback: "no_image.jpg") %>

<h4>監督名</h4>
<%= @movie.director %>

<h4>主演</h4>
<%= @movie.actor %>

<h4>あらすじ</h4>
<%= @movie.explain %>

<%= link_to "編集する", edit_admin_movie_path(@movie), class: "btn btn-success" %>