config/routes.rb
Rails.application.routes.draw do
  devise_for :admins, controllers: {
    sessions: 'admins/sessions',
    passwords: 'admins/sessions',
    registrations: 'admins/registrations',
  }
  # devise customersと被らないよう指定

  namespace :admin do
    root 'homes#top'
    resources :genres, only: [:index, :create, :edit, :update, :destroy]
    resources :customers, only: [:index, :show, :edit, :update]
      resources :movies, only: [:index, :new, :create, :show, :edit, :update] do
      resources :movie_comments, only: [:show, :update, :index, :edit, :destroy, :create]
      resource :favorites, only: [:create, :destroy]
    end
  end

  devise_for :customers, controllers: {
    sessions: 'customers/sessions',
    passwords: 'customers/sessions',
    registrations: 'customers/registrations',
  }
  get 'search/search'


  scope module: :public do
   root 'homes#top'
   get 'homes/about' => 'homes#about'
     resources :movies, only: [:new, :create, :index, :show, :create, :update] do
     resources :movie_comments, only: [:index, :show, :destroy, :create]
     resource :favorites, only: [:create, :destroy]
   end
   resources :customers, only: [:show, :edit, :update] do
   resource :relationships, only: [:create, :destroy]
   get 'mypage' => 'customers#mypage', as: 'mypage'
   get 'followings' => 'relationships#followings', as: 'followings'
   get 'followers' => 'relationships#followers', as: 'followers'
  member do
    patch 'withdrawal'
    get 'unsubscribe'
   end
  end
 end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/_footer.html.erb
<footer class="mt-5">
  <p class="text-center">© CopyRight t.movie.inc</p>
</footer>

app/views/layouts/_header.html.erb
<header>
  <nav class="navbar navbar-expand-lg navbar-danger bg-danger">
   <div class="container">
    <a class="navbar-brand " href="/"><%= image_tag 'to.red.png', class: 'icon' %></h1></a>
     <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarLinks" aria-controls="navbarLinks" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
     </button>
      <div id="navbarLinks">
        <ul class="navbar-nav ml-auto">

<!-- 検索フォーム -->
<!--カラム_or_cont = 文字列が含まれるものにマッチ-->
<div class="movie-search">
<%= search_form_for @q do |f| %>
  <%= f.search_field :title_or_director_or_actor_or_cast_or_actres_cont, placeholder: "作品・監督・役者名", class: "search-input" %>
  <%= f.submit "検索", class: "search-btn" %>
<% end %>
</div>

<!-- 会員がログイン時 -->
<% if customer_signed_in? %>
  <li class="border border-dark rounded" style= "padding:10px; margin:10px;">
    <%= link_to "作品一覧", movies_path, class: "btn btn-outline" %>
  </li>
  <li class="border border-dark rounded" style="padding:10px; margin:10px;">
    <%= link_to "About", homes_about_path, class: "btn btn-outline" %>
  </li>
  <li class="border border-dark rounded" style="padding:10px; margin:10px;">
    <%= link_to "マイページ", customer_path(current_customer), class: "btn btn-outline" %>
  </li>
  <li class="border border-dark rounded" style="padding:10px; margin:10px;">
    <%= link_to "ログアウト", destroy_customer_session_path, method: :delete, class: "btn btn-outline" %>
  </li>
<!--管理者がログイン時 -->
<% elsif admin_signed_in? %>
  <li class="border border-dark rounded text-dark" style= "padding:10px; margin:10px;">
    <%= link_to '作品 登録', new_admin_movie_path, class: 'btn btn-outline'%>
  </li>
  <li class="border border-dark rounded text-dark" style= "padding:10px; margin:10px;">
    <%= link_to "作品 一覧", admin_movies_path, class: "btn btn-outline" %>
  </li>
  <li class="border border-dark rounded text-dark" style= "padding:10px; margin:10px;">
    <%= link_to "会員 一覧", admin_customers_path, class: "btn btn-outline" %>
  </li>
  <li class="border border-dark rounded text-dark" style= "padding:10px; margin:10px;">
    <%= link_to "ジャンル一覧", admin_genres_path, class: "btn btn-outline" %>
  </li>
  <li class="border border-dark rounded text-dark" style= "padding:10px; margin:10px;">
    <%= link_to "ログアウト", destroy_admin_session_path, method: :delete, class: "btn btn-outline" %>
  </li>
<!-- 会員・管理者がログアウト時 -->
<% else %>
  <li class="border border-dark rounded text-dark" style= "padding:10px; margin:10px;">
    <%= link_to "作品一覧", movies_path, class: "btn btn-outline" %>
  </li>
  <li class="border border-dark rounded text-dark" style= "padding:10px; margin:10px;">
    <%= link_to "About", homes_about_path, class: "btn btn-outline" %>
  </li>
  <li class="border border-dark rounded text-dark" style= "padding:10px; margin:10px;">
    <%= link_to "新規登録", new_customer_registration_path, class: "btn btn-outline" %>
  </li>
  <li class="border border-dark rounded text-dark" style= "padding:10px; margin:10px;">
    <%= link_to "ログイン", new_customer_session_path, class: "btn btn-outline" %>
  </li>
<% end %>

       </ul>
     </div>
   </div>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>to.movie|映画レビューサイト</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
     <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script data-ad-client="ca-pub-2353973777635493" async src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
    <script src="https://kit.fontawesome.com/55153a0bf2.js" crossorigin="anonymous"></script>
    <link rel="stylesheet" type="text/css" href="//cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick.css"/>
　　<link rel="stylesheet" type="text/css" href="//cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick-theme.css"/>
　　<script type="text/javascript" src="//cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick.min.js"></script>
  </head>
<body>
  <main>
    <div class="movie-back">
     <%= render "layouts/header" %>
      <% if flash[:notice] %>
       <div class="notification is-info">
        <p class="notice"><%= notice %></p>
       </div>
      <% end %>
       <% if flash[:alert] %>
      <div class="notification is-danger">
       <p class="alert"><%= alert %></p>
      </div>
       <% end %>
    <%= yield %>
    </div>
  </main>
    <%= render "layouts/footer" %>
</body>
</html>